# Generated by Django 6.0.6 on 2026-06-21 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um número de telefone válido (10 a 15 dígitos).",
                                regex="^\\+?\\d{10,15}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Estado (UF)"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_modelo",
                    models.CharField(max_length=100, verbose_name="Nome do modelo"),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="Marca")),
                (
                    "motorizada",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a cadeira é motorizada (requisito para o kit).",
                        verbose_name="Motorizada",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Modelo de Cadeira",
                "verbose_name_plural": "Modelos de Cadeiras",
                "ordering": ["marca", "nome_modelo"],
                "unique_together": {("nome_modelo", "marca")},
            },
        ),
        migrations.CreateModel(
            name="PessoaFisica",
            fields=[
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pessoa_fisica",
                        serialize=False,
                        to="EasyRide.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um CPF válido (ex: 000.000.000-00).",
                                regex="^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "tipo_deficiencia",
                    models.CharField(
                        blank=True,
                        help_text="Descrição da deficiência motora do paciente.",
                        max_length=100,
                        verbose_name="Tipo de deficiência",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("paciente", "Paciente"),
                            ("familiar", "Familiar"),
                            ("cuidador", "Cuidador"),
                        ],
                        default="paciente",
                        help_text="Indica se o cadastro é do paciente, familiar ou cuidador.",
                        max_length=20,
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "comunicacao_verbal_preservada",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o paciente mantém a capacidade de comunicação verbal (relevante para o sistema de comandos de voz do kit).",
                        verbose_name="Comunicação verbal preservada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa Física",
                "verbose_name_plural": "Pessoas Físicas",
            },
        ),
        migrations.CreateModel(
            name="PessoaJuridica",
            fields=[
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pessoa_juridica",
                        serialize=False,
                        to="EasyRide.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Informe um CNPJ válido (ex: 00.000.000/0000-00).",
                                regex="^\\d{2}\\.?\\d{3}\\.?\\d{3}/?\\d{4}-?\\d{2}$",
                            )
                        ],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "tipo_instituicao",
                    models.CharField(
                        choices=[
                            ("clinica", "Clínica de Reabilitação"),
                            ("hospital", "Hospital"),
                            ("ong", "ONG / Instituição Social"),
                            ("universidade", "Universidade / Centro de Pesquisa"),
                            ("outro", "Outro"),
                        ],
                        default="clinica",
                        max_length=30,
                        verbose_name="Tipo de instituição",
                    ),
                ),
                (
                    "contato_responsavel",
                    models.CharField(
                        blank=True,
                        help_text="Nome da pessoa de contato na instituição.",
                        max_length=200,
                        verbose_name="Nome do responsável",
                    ),
                ),
                (
                    "cargo_responsavel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo do responsável"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa Jurídica",
                "verbose_name_plural": "Pessoas Jurídicas",
            },
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data/hora do registro"
                    ),
                ),
                (
                    "quantidade_estimada",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantidade de kits/cadeiras de interesse.",
                        verbose_name="Quantidade estimada",
                    ),
                ),
                (
                    "mensagem",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem ou observações adicionais do interessado.",
                        verbose_name="Mensagem",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("site_b2c", "Site - Formulário B2C"),
                            ("site_b2b", "Site - Formulário B2B"),
                            ("indicacao", "Indicação"),
                            ("evento", "Evento"),
                            ("outro", "Outro"),
                        ],
                        default="site_b2c",
                        max_length=20,
                        verbose_name="Origem do lead",
                    ),
                ),
                (
                    "status_lead",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("contatado", "Contatado"),
                            ("qualificado", "Qualificado"),
                            ("negociacao", "Em Negociação"),
                            ("convertido", "Convertido"),
                            ("perdido", "Perdido"),
                        ],
                        default="novo",
                        max_length=20,
                        verbose_name="Status do lead",
                    ),
                ),
                (
                    "aceite_termos",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o interessado aceitou os termos de uso e política de privacidade.",
                        verbose_name="Aceite dos termos",
                    ),
                ),
                (
                    "possui_cadeira",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o interessado já possui uma cadeira de rodas motorizada.",
                        verbose_name="Já possui cadeira motorizada",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interesses",
                        to="EasyRide.modelo",
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interesses",
                        to="EasyRide.pessoa",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interesse (Lead)",
                "verbose_name_plural": "Interesses (Leads)",
                "ordering": ["-data_hora"],
            },
        ),
    ]
