# Generated by Django 6.0.6 on 2026-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyRide", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="interesse",
            index=models.Index(fields=["status_lead"], name="idx_interesse_status"),
        ),
        migrations.AddIndex(
            model_name="interesse",
            index=models.Index(fields=["origem"], name="idx_interesse_origem"),
        ),
        migrations.AddIndex(
            model_name="interesse",
            index=models.Index(fields=["-data_hora"], name="idx_interesse_data"),
        ),
        migrations.AddIndex(
            model_name="interesse",
            index=models.Index(
                fields=["status_lead", "origem"], name="idx_interesse_status_origem"
            ),
        ),
        migrations.AddIndex(
            model_name="interesse",
            index=models.Index(
                fields=["pessoa", "-data_hora"], name="idx_interesse_pessoa_data"
            ),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["nome"], name="idx_pessoa_nome"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["estado"], name="idx_pessoa_estado"),
        ),
        migrations.AddIndex(
            model_name="pessoa",
            index=models.Index(fields=["-criado_em"], name="idx_pessoa_criado"),
        ),
    ]
