# Generated by Django 6.0.6 on 2026-06-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyRide", "0002_interesse_idx_interesse_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interesse",
            name="origem",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("indicacao", "Indicação"),
                    ("evento", "Evento"),
                    ("outro", "Outro"),
                ],
                default="outro",
                help_text="Canal pelo qual o interessado conheceu a EasyRide.",
                max_length=20,
                verbose_name="Como nos conheceu",
            ),
        ),
    ]
