# Generated by Django 6.0.6 on 2026-06-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyRide", "0003_alter_interesse_origem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoajuridica",
            name="tipo_instituicao",
            field=models.CharField(
                choices=[
                    ("clinica", "Clínica de Reabilitação"),
                    ("hospital", "Hospital"),
                    ("ong", "ONG / Instituição Social"),
                    ("outro", "Outro"),
                ],
                default="clinica",
                max_length=30,
                verbose_name="Tipo de instituição",
            ),
        ),
    ]
