# Generated by Django 6.0.6 on 2026-07-20 21:11

import EasyRide.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyRide', '0004_alter_pessoajuridica_tipo_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(help_text='Identificador do ícone a ser exibido no Frontend (ex: "microphone").', max_length=50, verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('foto', models.CharField(blank=True, help_text='URL da foto do depoente.', max_length=300, verbose_name='Foto')),
                ('texto', models.TextField(verbose_name='Texto do depoimento')),
                ('avaliacao', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=300, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes (FAQ)',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um CPF válido (ex: 000.000.000-00).', regex='^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$'), EasyRide.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um CNPJ válido (ex: 00.000.000/0000-00).', regex='^\\d{2}\\.?\\d{3}\\.?\\d{3}/?\\d{4}-?\\d{2}$'), EasyRide.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
    ]
