services:
  - type: web
    name: easyride-api
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: CACHE_BACKEND
        value: "database"
      - key: CACHE_TTL_CONTEUDO
        value: "900"
      - key: PYTHON_VERSION
        value: "3.13"
